name: Validate Action Private
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3 

      - name: Private Action
        uses: ./.github/actions/private/workflow-permission
        with:
          users: lincolnnery
