name: Validate Action Private
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v3
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: lincolnnery/gh-actions
          path: .github/actions/workflow-permission
      - name: Upload to S3 Dev
        run: |
          ls -la /home/runner/work/run-private-actions/run-private-actions/.github/actions/workflow-permission

      - name: Run My Action
        uses: ./.github/actions/workflow-permission




#      - name: Checkout source code
#        uses: actions/checkout@v3 
#
#      - name: Private Action
#        uses: ./.github/actions/private/workflow-permission
#        with:
#          users: lincolnnery
